/* 
 * Realtime Notification Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EndpointApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EndpointApiTests
    {
        private EndpointApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EndpointApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EndpointApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EndpointApi
            //Assert.IsInstanceOfType(typeof(EndpointApi), instance, "instance is a EndpointApi");
        }

        
        /// <summary>
        /// Test Endpointget
        /// </summary>
        [Test]
        public void EndpointgetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string stpServiceTicket = null;
            //EndpointGetRequest body = null;
            //var response = instance.Endpointget(stpServiceTicket, body);
            //Assert.IsInstanceOf<EndpointGetServiceResponse> (response, "response is EndpointGetServiceResponse");
        }
        
    }

}
