/* 
 * Realtime Notification Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EndpointResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EndpointResponseTests
    {
        // TODO uncomment below to declare an instance variable for EndpointResponse
        //private EndpointResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EndpointResponse
            //instance = new EndpointResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EndpointResponse
        /// </summary>
        [Test]
        public void EndpointResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EndpointResponse
            //Assert.IsInstanceOfType<EndpointResponse> (instance, "variable 'instance' is a EndpointResponse");
        }


        /// <summary>
        /// Test the property 'Headers'
        /// </summary>
        [Test]
        public void HeadersTest()
        {
            // TODO unit test for the property 'Headers'
        }
        /// <summary>
        /// Test the property 'BroadcastAddress'
        /// </summary>
        [Test]
        public void BroadcastAddressTest()
        {
            // TODO unit test for the property 'BroadcastAddress'
        }
        /// <summary>
        /// Test the property 'BroadcastBase'
        /// </summary>
        [Test]
        public void BroadcastBaseTest()
        {
            // TODO unit test for the property 'BroadcastBase'
        }

    }

}
