/* 
 * Realtime Notification Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing EndpointGetServiceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EndpointGetServiceResponseTests
    {
        // TODO uncomment below to declare an instance variable for EndpointGetServiceResponse
        //private EndpointGetServiceResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EndpointGetServiceResponse
            //instance = new EndpointGetServiceResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EndpointGetServiceResponse
        /// </summary>
        [Test]
        public void EndpointGetServiceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EndpointGetServiceResponse
            //Assert.IsInstanceOfType<EndpointGetServiceResponse> (instance, "variable 'instance' is a EndpointGetServiceResponse");
        }


        /// <summary>
        /// Test the property 'ResultCode'
        /// </summary>
        [Test]
        public void ResultCodeTest()
        {
            // TODO unit test for the property 'ResultCode'
        }
        /// <summary>
        /// Test the property 'ResultDescription'
        /// </summary>
        [Test]
        public void ResultDescriptionTest()
        {
            // TODO unit test for the property 'ResultDescription'
        }
        /// <summary>
        /// Test the property 'ResultType'
        /// </summary>
        [Test]
        public void ResultTypeTest()
        {
            // TODO unit test for the property 'ResultType'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Test]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Test]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

    }

}
