/* 
 * Realtime Notification Service
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IEndpointApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Realtime Notification Service Configuration
        /// </summary>
        /// <remarks>
        /// Returns connection parameters and url of notification endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>EndpointGetServiceResponse</returns>
        EndpointGetServiceResponse Endpointget (string stpServiceTicket, EndpointGetRequest body = null);

        /// <summary>
        /// Realtime Notification Service Configuration
        /// </summary>
        /// <remarks>
        /// Returns connection parameters and url of notification endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EndpointGetServiceResponse</returns>
        ApiResponse<EndpointGetServiceResponse> EndpointgetWithHttpInfo (string stpServiceTicket, EndpointGetRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Realtime Notification Service Configuration
        /// </summary>
        /// <remarks>
        /// Returns connection parameters and url of notification endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of EndpointGetServiceResponse</returns>
        System.Threading.Tasks.Task<EndpointGetServiceResponse> EndpointgetAsync (string stpServiceTicket, EndpointGetRequest body = null);

        /// <summary>
        /// Realtime Notification Service Configuration
        /// </summary>
        /// <remarks>
        /// Returns connection parameters and url of notification endpoint.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (EndpointGetServiceResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<EndpointGetServiceResponse>> EndpointgetAsyncWithHttpInfo (string stpServiceTicket, EndpointGetRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class EndpointApi : IEndpointApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="EndpointApi"/> class.
        /// </summary>
        /// <returns></returns>
        public EndpointApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EndpointApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public EndpointApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Realtime Notification Service Configuration Returns connection parameters and url of notification endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>EndpointGetServiceResponse</returns>
        public EndpointGetServiceResponse Endpointget (string stpServiceTicket, EndpointGetRequest body = null)
        {
             ApiResponse<EndpointGetServiceResponse> localVarResponse = EndpointgetWithHttpInfo(stpServiceTicket, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Realtime Notification Service Configuration Returns connection parameters and url of notification endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of EndpointGetServiceResponse</returns>
        public ApiResponse< EndpointGetServiceResponse > EndpointgetWithHttpInfo (string stpServiceTicket, EndpointGetRequest body = null)
        {
            // verify the required parameter 'stpServiceTicket' is set
            if (stpServiceTicket == null)
                throw new ApiException(400, "Missing required parameter 'stpServiceTicket' when calling EndpointApi->Endpointget");

            var localVarPath = "/endpoint/get";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (stpServiceTicket != null) localVarHeaderParams.Add("stp-service-ticket", Configuration.ApiClient.ParameterToString(stpServiceTicket)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Endpointget", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EndpointGetServiceResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EndpointGetServiceResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EndpointGetServiceResponse)));
        }

        /// <summary>
        /// Realtime Notification Service Configuration Returns connection parameters and url of notification endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of EndpointGetServiceResponse</returns>
        public async System.Threading.Tasks.Task<EndpointGetServiceResponse> EndpointgetAsync (string stpServiceTicket, EndpointGetRequest body = null)
        {
             ApiResponse<EndpointGetServiceResponse> localVarResponse = await EndpointgetAsyncWithHttpInfo(stpServiceTicket, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Realtime Notification Service Configuration Returns connection parameters and url of notification endpoint.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="stpServiceTicket">STP Service ST Header</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (EndpointGetServiceResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<EndpointGetServiceResponse>> EndpointgetAsyncWithHttpInfo (string stpServiceTicket, EndpointGetRequest body = null)
        {
            // verify the required parameter 'stpServiceTicket' is set
            if (stpServiceTicket == null)
                throw new ApiException(400, "Missing required parameter 'stpServiceTicket' when calling EndpointApi->Endpointget");

            var localVarPath = "/endpoint/get";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (stpServiceTicket != null) localVarHeaderParams.Add("stp-service-ticket", Configuration.ApiClient.ParameterToString(stpServiceTicket)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Endpointget", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<EndpointGetServiceResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (EndpointGetServiceResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(EndpointGetServiceResponse)));
        }

    }
}
